import streamlit as st

from valact.settings import COLLECTION_LABELS, COLLECTIONS


def clear_cache():
    st.cache_data.clear()


def clear_cache_button():
    st.sidebar.button(
        label="Clear cache",
        use_container_width=True,
        on_click=clear_cache,
        help="Reset list of documents and pregenerated summary",
    )


def main():
    st.set_page_config(page_title="How-to", page_icon="📖")

    st.title("How to use the Q&A Machine")
    st.write(
        "This web app lets you ask questions about actuarial documents and receive "
        "answers generated by a language model augmented with information retrieved from those documents."
    )
    st.write(
        "Harness the model with responsibility and accountability. The retrieval process is "
        "designed for transparency and verifiability."
    )

    st.header("Step 1: Select a Collection of Actuarial Documents")
    st.write(
        "Responses can differ by domain. Select the collection your question falls under."
    )
    st.write("Available document collections:")
    st.write("- " + "\n- ".join(COLLECTION_LABELS[c] for c in COLLECTIONS))

    st.header("Step 2: Decide Whether to Ask About a Specific Document")
    st.write(
        'Within a domain, your question may target a single document. Choose it for the most '
        'relevant response. If unsure, leave the selection as "All" and the retrieval process '
        "will pull from all documents in the collection."
    )

    st.subheader("Step 2a: Preview Document Summaries")
    st.write(
        "AI-generated summaries help you understand what each document covers. Always refer "
        "to the source documents for full details."
    )
    st.write("**See the sidebar to review summaries.**")

    st.header("Step 3: Ask Your Question")
    st.write("Phrase your question concisely. Spell out abbreviations. Examples:")
    for example in [
        "*Explain ASOP No. 14.*",
        "*Explain Bermuda Solvency Capital Requirement* (better than *Explain BSCR*).",
    ]:
        st.write("- " + example)

    st.subheader("Step 3a: Adjust RAG Parameters")
    st.write("You can tune the retrieval pipeline:")
    st.write(
        "- **Top N Sources to View**: how many retrieved sections to display. The pipeline "
        "fetches 40 candidates from the vector store, reranks to the top 10 with Cohere, "
        "and shows the top N you choose."
    )
    st.write(
        "- **Diversity Search (MMR)**: reduces redundancy among the candidates before reranking, "
        "useful for broader perspective on a topic."
    )

    st.subheader("Step 3b: Clear History")
    st.write(
        "Chat history influences retrieval and the model's responses. Clear history when "
        "switching collections or topics."
    )

    st.header("Step 4: Review Responses")
    st.write(
        "Review the model's response alongside the retrieved sections it cites. Always verify "
        "against the source material — model output does not replace actuarial judgment."
    )

    st.header("Step 5: Review Source Documents")
    st.write(
        "Use retrieval results to narrow where to focus, then read the official documentation yourself."
    )


if __name__ == "__main__":
    main()
    clear_cache_button()
